### PR TITLE
Storybook improvements

### PR DESCRIPTION
**Pull request by longyulongyu**
## Summary
- Update to 8.3.3
- Change the imports so that each story doesn't load everything
- Isolate the logic to create `Checkout` and `ComponentContainer` to give us more flexibility writing stories
- Remove the loaders in the `preview`

## Tested scenarios

**Fixed issue**:

### CODE REVIEW

**Comment by asumaran** [comment]
Hey there,

How is StoryBook supposed to be run? I'm trying to test the Adyen integration with Apple Pay, but I haven’t been able to because I'm encountering errors.


```
:3020/iframe.html?viewMode=story&id=cards-bancontact--default&args=&globals=:1 Access to fetch at 'https://checkoutshopper-test.adyen.com/checkoutshopper/v1/sessions/CS0D34D085A85F471C/setup?clientKey=test_PHC...' from origin 'https://localhost:3020' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
```

This is my env file:

```
API_VERSION=v69

CHECKOUT_API_KEY=AQEth...
MERCHANT_ACCOUNT=MyMerchantAccount
TESTING_ENVIRONMENT=test
ORIGIN=https://localhost:3020

# Playground Port
PORT=3020

#ClientKey - generated per WS User in the Backoffice
CLIENT_KEY=test_....

# test / live
CLIENT_ENV=test

####################
# SecuredFields.html src
# - Comment in if loading securedFields from local node server
# - If commenting in - also make sure IS_HTTPS=false
####################
#SF_ENV=http://localhost:8011/

# Enable https. When set it to true, you need to create your own self-signed certificates
# Follow https://web.dev/how-to-use-local-https/
IS_HTTPS=true
# absolute path of your cert and key
CERT_PATH=/Users/asumaran/Developer/adyen-web/localhost.pem
CERT_KEY_PATH=/Users/asumaran/Developer/adyen-web/localhost-key.pem
```

What am I doing wrong?

**Comment by longyulongyu** [comment]
> run

Hi Alfredo, my suspect is either your `CLIENT_KEY` or `CHECKOUT_API_KEY` was not configured correctly, as you shouldn't have cors errors. 
Do you have the same issue running `yarn build` and `yarn start`. This is another playground you could try.

**Comment by asumaran** [comment]
>Do you have the same issue running yarn build and yarn start? This is another playground you could try.

Same CORS error.

**Comment by asumaran** [comment]
@longyulongyu I was able to make it work. Apple Pay is still not working for me.

It only worked after adding `https://localhost:3020` to the list of allowed origins, so I think you should consider adding that to the documentation.

Additionally, the Apple Pay Storybook isn’t working as expected. I had to tweak the code a bit to get it running. Both “Apple Pay” and “Apple Pay Express” are not functioning because some props are missing. In [this file](https://github.com/Adyen/adyen-web/blob/2f4a4c0186e0c0218b957158cab98115e89676a7/packages/lib/storybook/stories/wallets/ApplePay.stories.tsx#L19) and [this one](https://github.com/Adyen/adyen-web/blob/2f4a4c0186e0c0218b957158cab98115e89676a7/packages/lib/storybook/stories/wallets/ApplePayExpress.stories.tsx#L151), we need to add the following:

```
args: {
    componentConfiguration: {
        configuration: {
            merchantName: 'My Merchant Name',
            merchantId: 'MyMerchantID'
        }
    }
}
```

However, even with this, it’s still not working. I noticed a request is being made to `https://checkoutshopper-test.adyen.com/checkoutshopper/v1/applePay/sessions?clientKey=test_JYX...
`, but I receive this response:

```
{
    "status": 422,
    "errorCode": "000",
    "message": "Payment Services Exception merchantId=2EA0321F0... unauthorized to process transactions on behalf of merchantId=4DC056F... reason=4DC056F... is not a registered merchant in WWDR and isn't properly authorized via Mass Enablement, either.",
    "errorType": "validation"
}
```

We’ve used the code from the documentation but haven’t been able to successfully process an order so far.

Any help would be appreciated, as we’re struggling to get Apple Pay working with Adyen. I’m curious—has it worked for you in Storybook or any other instance? Can you confirm please?

**Comment by longyulongyu** [comment]
Hi @asumaran yes I was supposed to show you this documentation about - [adding allowed origin](https://docs.adyen.com/development-resources/client-side-authentication/#allowed-origins).

**Comment by ribeiroguilherme** [comment]
Hey @asumaran ,

> Additionally, the Apple Pay Storybook isn’t working as expected. I had to tweak the code a bit to get it running. Both “Apple Pay” and “Apple Pay Express” are not functioning because some props are missing.

These props must come from your /paymentMethods response and they will be propagated to the ApplePay component. It should not be needed to manually set them!

> However, even with this, it’s still not working. I noticed a request is being made to https://checkoutshopper-test.adyen.com/checkoutshopper/v1/applePay/sessions?clientKey=test_JYX... , but I receive this response:

This error response seems like a configuration issue, perhaps in your account in our backoffice. I suggest to reach out to [support@adyen.com](mailto:support@adyen.com) so they can take a look into that.

> Any help would be appreciated, as we’re struggling to get Apple Pay working with Adyen. I’m curious—has it worked for you in Storybook or any other instance? Can you confirm please?

It has been quite hard for us to test ApplePay on our localhost setup to be honest. We have it in the Storybook mainly to showcase the code for the Express flow, but we are not able to run it properly. We are aiming to do that once we deploy our Storybook live, so we will have https URL and proper domain that can be validated.

Our current workaround for that is to test it using Netlify. We have a simple web application running there where we can deploy and test our code/components in a live domain having https out of the box and domain validated. Perhaps it could be something that you can explore.

**Pull request merged**
