### PR TITLE
Fix Element reference error when importing library outside browser context

### PR DESCRIPTION
**Pull request by jonlambert**
## Summary

When importing the `@adyen/adyen-web` library in a server-side context, [the app will crash](https://github.com/Adyen/adyen-web/issues/1315#issuecomment-977815471) just through the import alone. This means you can't simply perform a runtime check before instantiating the AdyenCheckout class, and requires you to dynamically import any components that use this library which adds quite a lot of overhead. 

This PR checks for the presence of `Element`, `navigator` and `window` objects before referencing at the top-level of each file. I haven't bothered adding presence checks within function calls, etc, as full SSR support would fall outside the scope of this PR. But at least now the library can be imported in a server-side context without crashing or requiring dynamic importing.

I managed to spin up a dev environment locally to reproduce and test this; hopefully someone with a more in-depth knowledge of the codebase can review 🙂 Would be great to get thoughts.

Thanks a lot.

**Fixed issue**:  #1315, #902, #233

### CODE REVIEW

**Comment by jonlambert** [comment]
Have updated to check for the presence of `Element`, `navigator` and `window `objects whenever they're used at the top level of a file.

**Comment by jonlambert** [comment]
(There may be some crossover with work done in #1343 here)

**Comment by jonlambert** [comment]
Hey @ribeiroguilherme – further to our chat in #1315 do you have any thoughts on this? Sorry to nudge, but we're using my fork at the moment and before we proceed much further it would be good to get an idea of whether this might be merged or not 🙂 Thanks a lot.

**Review by ribeiroguilherme — APPROVED** [review]
@jonlambert thanks for contributing to the project. I tested in a `next.js` project and worked well. 👍

**Pull request merged**
